# Generated by Django 2.0.5 on 2018-05-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nomMovimiento', models.CharField(choices=[('E', 'entrada'), ('S', 'salida')], default='E', max_length=1)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.marca')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.producto')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='idProducto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagina.producto'),
        ),
    ]
